# Generated by Django 5.1.4 on 2025-01-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='CarImages/')),
            ],
        ),
    ]
